### ISSUE TITLE
多账号处理

### ISSUE THREAD

**Issue by doublog** [BlueSkyXN/189Cloud-Checkin#2]
请问大佬，多账号用一个脚本有办法实现么？我现在是直接复制了py，然后分开执行的。。
有没有办法直接把多账号写入同一个脚本，直接执行？

**Comment by BlueSkyXN** [comment]
不是太方便改，需要判断字符，还不如多开来的简单
如果你是服务器运行，可以写个bash调用多个py
如果是云函数直接镜像就完事

**Comment by doublog** [comment]
> 不是太方便改，需要判断字符，还不如多开来的简单
> 如果你是服务器运行，可以写个bash调用多个py
> 如果是云函数直接镜像就完事

我现在就是这样执行的，用的多任务执行。
