### ISSUE TITLE
老大，能不能弄个docker的版本！！

### ISSUE THREAD

**Issue by hyy34** [BlueSkyXN/189Cloud-Checkin#4]
服务器弄的无法安装依赖。估计解决起来很费事，如果有docker的版本就带劲了。

**Comment by BlueSkyXN** [comment]
> 服务器弄的无法安装依赖。估计解决起来很费事，如果有docker的版本就带劲了。

为何不用云函数，简单要死

**Comment by cdlaimin** [comment]
可以自己弄呀 找一个python3的docker镜像 进入安装python的库就可以了
